POST http://localhost:8000/api/register/ HTTP/1.1 
Content-Type: application/json

{
    "email":"khan@example.com",
    "password":"user@123",
    "confirm_password":"user@123"
}
###


POST http://localhost:8000/api/login/ HTTP/1.1
Content-Type: application/json

{
    "email":"abrar@example.com",
    "password":"user@123"
}

###

POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2NzYyODg0NSwiaWF0IjoxNzY3NDU2MDQ1LCJqdGkiOiJkM2RjMDY4ZGI0YjU0ZGNjYjlkMzQ5YjllYWFjNTNlMCIsInVzZXJfaWQiOiIxIn0.be0g-MSn18szOb-sddRydboY0bFqNKl6ZZHenpUdqlQ"
}