# Generated by Django 6.0 on 2026-01-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_youtubevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='video_id',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
