# Generated by Django 6.0 on 2026-01-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_youtubevideo_video_id_alter_youtubevideo_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="youtubevideo",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
