# Generated by Django 6.0 on 2026-05-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_document_summary_youtubevideo_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
